### PR TITLE
fix: Fixed background color inconsistencies in UI code

### PR DESCRIPTION
**Pull request by ccarril3**
Fixed background color inconsistencies in UI code

### CODE REVIEW

**Comment by hmahmoo3** [comment]
Recommend merging at at commit [d81ed8e](https://github.com/JH-Byte-Busters/601-Group-Project/pull/7/commits/d81ed8e98ee0c7acb485984f21bfcc98179b9568) rather than the most recent commit [01891bb](https://github.com/JH-Byte-Busters/601-Group-Project/commit/01891bb887486a195f399c92cded4514fdfb8b5d). When using QT Designer running into issues with opening the UI file for the "Player Menu" and since that's the main tool used for the UI development rather not introduce errors or try to investigate the issue.

The UI coloring can be addressed in a subsequent issue/branch. 

image

**Comment by ccarril3** [comment]
Errors can be debug and fixed on the go. That is the pupose of collaborating. We do need to wait until we have the perfect code to merge. As I said, this code is just for reference at this point, not to be run as whole. At least not yet. I need some base code to start playing around. From my professional experience, having different non-merged branches all over will provoke confusion...

**Comment by ccarril3** [comment]
Errors can be debug and fixed on the go. That is the purpose of collaborating. We do need to wait until we have the perfect code to merge. As I said, this code is just for reference at this point, not to be run as whole. At least not yet. I need some base code to start playing around. From my experience, having different non-merged branches all over will just create confusion...

**Comment by ccarril3** [comment]
Errors can be debugged and fixed on the go. That is the purpose of collaborating. We do need to wait until we have the perfect code to merge. As I said, this code is just for reference at this point, not to be run as whole. At least not yet. I need some base code to start playing around. From my experience, having different non-merged branches all over will just create confusion...

**Comment by ccarril3** [comment]
Errors can be debugged and fixed on the go. That is the purpose of collaborating. We don't need to wait until we have the perfect code to merge. As I said, this code is just for reference at this point, not to be run as whole. At least not yet. I need some base code to start playing around. So please feel free to merge from [d81ed8e](https://github.com/JH-Byte-Busters/601-Group-Project/pull/7/commits/d81ed8e98ee0c7acb485984f21bfcc98179b9568) asap if that is what you think is the right action, @hmahmoo3

**Review by hmahmoo3 — CHANGES_REQUESTED** [review]
Merge GUI updates from here.

EDIT: IGNORE. Was thinking it would create another merge request. Sorry.

**Comment by hmahmoo3** [comment]
I guess we can just merge this in and then my next branch should fix the changes https://github.com/JH-Byte-Busters/601-Group-Project/tree/GUI_development_HAMZA.

Sorry for any issues.

**Comment by ccarril3** [comment]
Sure. So could you please approve and merge, @hmahmoo3 and @AntHanna23?

**Comment by AntHanna23** [comment]
Try adding some docs on how to start and use the code. This way it is easy for me and cameron to use it. Also is this code not starting like hazma shows at the beginning. We shouldnt merge broken code just because. Theres not real benefit to that

**Comment by ccarril3** [comment]
The benefit on merging broken code in this case is that we can all try to fix it. At this point, all the code is broken. Not sure why we are making a big deal out of this?

**Comment by AntHanna23** [comment]
Why wouldn't I just check out that branch and look at it? If there's code you need help with tell us the branch name and we can look at it there

**Pull request closed without merging**
